### ISSUE TITLE
BUG (regression): scaling bug reopened on version 1.1.3 

### ISSUE THREAD

**Issue by alesimula** [zathras/jovial_svg#66]
Hello

It seems the [issue #14](https://github.com/zathras/jovial_svg/issues/14) I had opened more than a year and a half ago has been reintroduced on version 1.1.3.

I have managed to trace back to the commit that broke it, it was [this one \(Implement tspan\)](https://github.com/zathras/jovial_svg/commit/e6c2609b35cdd16f98a5b7a79410feced318f223);

Ironically removing the following code from avd_parser.dart (line 247), that you introduced to fix this very bug, seems to fix it (but you may have more insights as to why):

`root.transform =
              MutableAffine.scale(scaledWidth / width, scaledHeight / height);`

**Comment by zathras** [comment]
Thanks for finding this.  I haven't verified the bug yet, but I believe that it's present.  The putback for 1.1.3 was a pretty big change to the way AVDs are handled - starting with 1.1.3, the library builds the same in-memory tree for AVDs as it does for SVGs.  It's not all that shocking that something like this slipped through the cracks with that change - it's probably scaling twice, or something dumb like that.

In a sense, the real flaw is that there wasn't a regression test for issue 14 to catch this.  In the current `jovial_svg` (and for quite some time), there are a large number of tests that check the rendering of various assets, but I see I have a bunch of basically orphaned AVD assets in demo/assets/test:
```
-rw-rw-r-- 1 billf billf  5139 May  3  2022 issue_13_forgiving_1_avd.si
-rw-rw-r-- 1 billf billf 13077 May  3  2022 issue_13_forgiving_1_avd.xml
-rw-rw-r-- 1 billf billf   875 May  3  2022 issue_13_forgiving_2_avd.si
-rw-rw-r-- 1 billf billf  2320 May  3  2022 issue_13_forgiving_2_avd.xml
-rw-rw-r-- 1 billf billf   439 May  3  2022 issue_14_scale_1_avd.si
-rw-rw-r-- 1 billf billf   667 May  3  2022 issue_14_scale_1_avd.xml
-rw-rw-r-- 1 billf billf   439 May  3  2022 issue_14_scale_2_avd.si
-rw-rw-r-- 1 billf billf   666 May  3  2022 issue_14_scale_2_avd.xml
-rw-rw-r-- 1 billf billf   405 May  3  2022 issue_14_scale_3_avd.si
-rw-rw-r-- 1 billf billf   609 May  3  2022 issue_14_scale_3_avd.xml
-rw-rw-r-- 1 billf billf   413 May  3  2022 issue_14_size_avd.si
-rw-rw-r-- 1 billf billf   620 May  3  2022 issue_14_size_avd.xml
```
The first thing I should do is move these into the regression tests, render them with 1.1.2, and then check the rendering against the current version of `jovial_svg` to see if other things have broken.

The eventual fix for the issue 14 might be as simple as removing the `root.transform` line you identified -- maybe the new way of handling AVD files in 1.1.3 is already taking care of this scaling, or something.  I'll have to dive in the code to verify this.

**Comment by zathras** [comment]
Yep, the bug was super dumb.  Once the AVD is scaled, the width and height become the *scaled* width and height, not the original width and height.  I did add test cases for this into the regression tests.

I published as 1.1.16-rc.2; let me know if this works, or if you see issues with other AVDs or something.  When I hear it's OK, I'll publish 1.1.17.

**Comment by alesimula** [comment]
@zathras It seems to be working with the lines you added with all icons I tested:
```width = scaledWidth;
height = scaledHeight;```

under `root.transform = MutableAffine.scale(scaledWidth / width, scaledHeight / height);`

I'm still not sure why removing the scaling code alltogether seems to bear no effect on my end, rendering these icons the same way as it would with your fix

**Comment by zathras** [comment]
> I'm still not sure why removing the scaling code alltogether seems to bear no effect on my end,

I'd have to look at your code to be 100% sure, but I'm pretty confident that what's happening is that it's scaling the right amount, but sort of for the wrong reason.  You should see different results if you turn off scaling, e.g. in the widget in your app.

To give an example, say the underlying drawing operations in the icon gave a 100x100 icon, but the viewport stuff in the AVD resulted in a 500x500 icon.  Before the fix, you'd have a 500x500 icon that claimed its width and height was 100x100.  Without the scaling code you'd have a 100x100 icon that claimed to be 100x100.  With the new fix, you'd correctly have a 500x500 icon that claimed to be 500x500.  If the widget is scaling to fit, either of the last two would work.

Anyhoo, I'll promote this to a 1.1.16 release pretty soon.

**Comment by alesimula** [comment]
@zathras That might be the case

I'm using [this widget](https://github.com/alesimula/wsa_pacman/blob/main/lib/widget/adaptive_icon.dart) to display Android adaptive icons (although I'm scaling them by a fixed amount [1.5x], which is the default Android uses to scale both background and foreground of an adaptive icon)... I remember the icons being broken even when using that widget before you fixed [issue #14](https://github.com/zathras/jovial_svg/issues/14).

By the way, I'm not sure whether it falls within the scope of your library, but you can integrate that widget if you think it may be a useful addition, it displays Android adaptive icons (with foreground + background or foreground + color) with customizable radius (between 0.0 [square] and 1.0 [circle])

**Comment by zathras** [comment]
Thanks, but that sounds a little Android-specific for this library.  I'd hate to get iOS developers submitting issues telling me it is Not The Way, or something :-)

Fix published as 1.1.16
